### PR TITLE
Add function that masks the Bear Ridge grounded iceberg region within the bathymetry file

### PR DESCRIPTION
**Pull request by brogalla**
Called within process_topo when input parameter bear_ridge=True. The code is similar to the mitgcm_python make_domain (https://github.com/knaughten/mitgcm_python/blob/master/make_domain.py) function add_bear_ridge_bergs, with a change to the method for the northern part. I've also adjusted the bounds for the region defined as Bear Ridge within constants.py to create the best looking masking for the current grid.

### CODE REVIEW

**Comment by brogalla** [comment]
To see the change to the bathymetry in my test, scroll to the bottom of the following notebook: https://github.com/brogalla/analysis-birgal/blob/master/nemo_config_setup/test-bear-ridge.ipynb

**Comment by knaughten** [comment]
Just one concern about this: the helper function is below the calling function in make_domain.py. Python can be finicky about this; are you sure it runs without having them in the other order?

**Comment by brogalla** [comment]
Yes, it runs fine with the current order. Happy to move it up above the process_topo function to prevent any potential issues though.

**Comment by knaughten** [comment]
Interesting. I guess it's only when you have a __name__=='main' function that the order matters. I'll accept the change as is but let's keep an eye on it in case it causes issues in the future.

**Pull request merged**
